"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type AdminBlogPost = {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  content: string;
  seo_title: string | null;
  seo_description: string | null;
  published: boolean;
  auto_generated: boolean;
  author_name: string | null;
  created_at: string;
  published_at: string | null;
};

type BlogAdminResponse = {
  generatedToday: boolean;
  posts: AdminBlogPost[];
};

const ADMIN_EMAIL_STORAGE_KEY = "inconnect:admin-blog-email";

export function AdminBlogDashboard() {
  const [adminEmail, setAdminEmail] = useState("");
  const [error, setError] = useState("");
  const [generatedToday, setGeneratedToday] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [posts, setPosts] = useState<AdminBlogPost[]>([]);
  const [success, setSuccess] = useState("");

  useEffect(() => {
    const storedEmail = window.localStorage.getItem(ADMIN_EMAIL_STORAGE_KEY);
    if (storedEmail) setAdminEmail(storedEmail);
  }, []);

  const draftPosts = useMemo(() => posts.filter((post) => !post.published), [posts]);
  const publishedPosts = useMemo(() => posts.filter((post) => post.published), [posts]);
  const autoGeneratedPosts = useMemo(
    () => posts.filter((post) => post.auto_generated),
    [posts],
  );

  async function loadPosts(nextEmail = adminEmail) {
    if (!nextEmail.trim()) {
      setError("Admin email is required.");
      return;
    }

    setError("");
    setSuccess("");
    setIsLoading(true);
    window.localStorage.setItem(ADMIN_EMAIL_STORAGE_KEY, nextEmail.trim());

    try {
      const params = new URLSearchParams({ email: nextEmail.trim() });
      const response = await fetch(`/api/admin/blog?${params.toString()}`, {
        cache: "no-store",
      });
      const payload = (await response.json().catch(() => null)) as
        | BlogAdminResponse
        | { error?: string; details?: string }
        | null;

      if (!response.ok || !payload || !("posts" in payload)) {
        throw new Error(
          payload && "error" in payload && payload.error
            ? payload.error
            : "Blog posts could not be loaded.",
        );
      }

      setGeneratedToday(payload.generatedToday);
      setPosts(payload.posts);
    } catch (loadError) {
      setError(loadError instanceof Error ? loadError.message : "Blog posts could not be loaded.");
    } finally {
      setIsLoading(false);
    }
  }

  async function handleLogin(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    await loadPosts();
  }

  async function generateDraft() {
    setError("");
    setSuccess("");
    setIsGenerating(true);

    try {
      const response = await fetch("/api/admin/blog", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email: adminEmail }),
      });
      const payload = (await response.json().catch(() => null)) as
        | { error?: string; details?: string; post?: { title?: string } }
        | null;

      if (!response.ok) {
        throw new Error(payload?.details || payload?.error || "Blog draft could not be generated.");
      }

      setSuccess(`Generated draft${payload?.post?.title ? `: ${payload.post.title}` : "."}`);
      await loadPosts();
    } catch (generateError) {
      setError(
        generateError instanceof Error
          ? generateError.message
          : "Blog draft could not be generated.",
      );
    } finally {
      setIsGenerating(false);
    }
  }

  async function updatePost(
    post: AdminBlogPost,
    patch: Record<string, string | boolean | null>,
    successMessage: string,
  ) {
    setError("");
    setSuccess("");

    try {
      const response = await fetch("/api/admin/blog", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email: adminEmail, id: post.id, ...patch }),
      });
      const payload = (await response.json().catch(() => null)) as
        | { error?: string; details?: string; post?: AdminBlogPost }
        | null;

      if (!response.ok || !payload?.post) {
        throw new Error(payload?.details || payload?.error || "Blog post could not be updated.");
      }

      setPosts((currentPosts) =>
        currentPosts.map((currentPost) =>
          currentPost.id === payload.post?.id ? payload.post : currentPost,
        ),
      );
      setSuccess(successMessage);
    } catch (updateError) {
      setError(updateError instanceof Error ? updateError.message : "Blog post could not be updated.");
    }
  }

  async function deletePost(post: AdminBlogPost) {
    if (!window.confirm(`Delete "${post.title}"?`)) return;
    setError("");
    setSuccess("");

    try {
      const response = await fetch("/api/admin/blog", {
        method: "DELETE",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email: adminEmail, id: post.id }),
      });
      const payload = (await response.json().catch(() => null)) as
        | { error?: string; details?: string }
        | null;

      if (!response.ok) {
        throw new Error(payload?.details || payload?.error || "Blog post could not be deleted.");
      }

      setPosts((currentPosts) => currentPosts.filter((item) => item.id !== post.id));
      setSuccess("Blog post deleted.");
    } catch (deleteError) {
      setError(deleteError instanceof Error ? deleteError.message : "Blog post could not be deleted.");
    }
  }

  return (
    <section className="px-5 py-10 sm:px-8 lg:px-10">
      <div className="mx-auto max-w-7xl">
        <p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#0A66C2]">
          Admin Blog CMS
        </p>
        <h1 className="mt-3 text-3xl font-semibold text-[#191919]">
          Review AI-generated blog drafts.
        </h1>
        <p className="mt-3 max-w-3xl text-sm leading-6 text-[#666666]">
          Daily generation creates drafts by default. Publish only after review, or
          enable automatic publishing later with AUTO_PUBLISH_BLOG=true.
        </p>

        <form
          className="mt-6 flex flex-col gap-3 rounded-lg border border-[#D9DDE3] bg-white p-4 sm:flex-row sm:items-end"
          onSubmit={handleLogin}
        >
          <label className="flex-1 text-sm font-semibold text-[#191919]">
            Admin email
            <input
              className="mt-2 w-full rounded-lg border border-[#D9DDE3] px-3 py-3 text-sm outline-none transition focus:border-[#0A66C2] focus:ring-2 focus:ring-[#0A66C2]/15"
              onChange={(event) => setAdminEmail(event.target.value)}
              placeholder="founder@example.com"
              type="email"
              value={adminEmail}
            />
          </label>
          <button
            className="rounded-lg bg-[#4A6FD0] px-5 py-3 text-sm font-semibold text-white transition hover:bg-[#3859B8] disabled:bg-[#D9DDE3] disabled:text-[#666666]"
            disabled={isLoading}
            type="submit"
          >
            {isLoading ? "Loading..." : "Load Posts"}
          </button>
          <button
            className="rounded-lg bg-[#4A6FD0] px-5 py-3 text-sm font-semibold text-white transition hover:bg-[#3859B8] disabled:bg-[#D9DDE3] disabled:text-[#666666]"
            disabled={isGenerating || !adminEmail.trim()}
            onClick={generateDraft}
            type="button"
          >
            {isGenerating ? "Generating..." : "Regenerate"}
          </button>
        </form>

        {(error || success) && (
          <div
            className={`mt-4 rounded-lg border p-4 text-sm font-semibold ${
              error
                ? "border-red-200 bg-red-50 text-red-800"
                : "border-[#B9D8F5] bg-[#F3F7FD] text-[#0A66C2]"
            }`}
          >
            {error || success}
          </div>
        )}

        <div className="mt-6 grid gap-4 md:grid-cols-3">
          <StatusCard label="Generated Today" value={generatedToday ? "Yes" : "No"} />
          <StatusCard label="Draft Posts" value={String(draftPosts.length)} />
          <StatusCard label="Published Posts" value={String(publishedPosts.length)} />
        </div>

        <AdminPostSection
          adminEmail={adminEmail}
          emptyText="No draft posts yet."
          onDelete={deletePost}
          onUpdate={updatePost}
          posts={draftPosts}
          title="Draft Posts"
        />
        <AdminPostSection
          adminEmail={adminEmail}
          emptyText="No published posts yet."
          onDelete={deletePost}
          onUpdate={updatePost}
          posts={publishedPosts}
          title="Published Posts"
        />
        <AdminPostSection
          adminEmail={adminEmail}
          emptyText="No auto-generated posts yet."
          onDelete={deletePost}
          onUpdate={updatePost}
          posts={autoGeneratedPosts}
          title="Auto-generated Posts"
        />
      </div>
    </section>
  );
}

function StatusCard({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border border-[#D9DDE3] bg-white p-4">
      <p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#0A66C2]">
        {label}
      </p>
      <p className="mt-2 text-2xl font-semibold text-[#191919]">{value}</p>
    </div>
  );
}

function AdminPostSection({
  adminEmail,
  emptyText,
  onDelete,
  onUpdate,
  posts,
  title,
}: {
  adminEmail: string;
  emptyText: string;
  onDelete: (post: AdminBlogPost) => void;
  onUpdate: (
    post: AdminBlogPost,
    patch: Record<string, string | boolean | null>,
    successMessage: string,
  ) => void;
  posts: AdminBlogPost[];
  title: string;
}) {
  return (
    <section className="mt-8">
      <h2 className="text-2xl font-semibold text-[#191919]">{title}</h2>
      <div className="mt-4 grid gap-5">
        {posts.length === 0 && (
          <div className="rounded-lg border border-[#D9DDE3] bg-white p-5 text-sm text-[#666666]">
            {emptyText}
          </div>
        )}
        {posts.map((post) => (
          <AdminPostEditor
            adminEmail={adminEmail}
            key={post.id}
            onDelete={onDelete}
            onUpdate={onUpdate}
            post={post}
          />
        ))}
      </div>
    </section>
  );
}

function AdminPostEditor({
  onDelete,
  onUpdate,
  post,
}: {
  adminEmail: string;
  onDelete: (post: AdminBlogPost) => void;
  onUpdate: (
    post: AdminBlogPost,
    patch: Record<string, string | boolean | null>,
    successMessage: string,
  ) => void;
  post: AdminBlogPost;
}) {
  const [content, setContent] = useState(post.content);
  const [excerpt, setExcerpt] = useState(post.excerpt);
  const [seoDescription, setSeoDescription] = useState(post.seo_description ?? "");
  const [seoTitle, setSeoTitle] = useState(post.seo_title ?? "");
  const [title, setTitle] = useState(post.title);

  useEffect(() => {
    setContent(post.content);
    setExcerpt(post.excerpt);
    setSeoDescription(post.seo_description ?? "");
    setSeoTitle(post.seo_title ?? "");
    setTitle(post.title);
  }, [post]);

  return (
    <article className="rounded-lg border border-[#D9DDE3] bg-white p-5 shadow-[0_8px_24px_rgba(10,25,47,0.05)]">
      <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between">
        <div>
          <p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#0A66C2]">
            {post.category} {post.auto_generated ? "Auto-generated" : "Manual"}
          </p>
          <p className="mt-2 text-sm text-[#666666]">
            /blog/{post.slug} · {post.published ? "Published" : "Draft"}
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          <button
            className="rounded-lg bg-[#4A6FD0] px-4 py-2 text-sm font-semibold text-white transition hover:bg-[#3859B8]"
            onClick={() =>
              onUpdate(
                post,
                { content, excerpt, seoDescription, seoTitle, title },
                "Blog post saved.",
              )
            }
            type="button"
          >
            Save
          </button>
          <button
            className="rounded-lg bg-[#4A6FD0] px-4 py-2 text-sm font-semibold text-white transition hover:bg-[#3859B8]"
            onClick={() =>
              onUpdate(
                post,
                { published: !post.published },
                post.published ? "Blog post unpublished." : "Blog post published.",
              )
            }
            type="button"
          >
            {post.published ? "Unpublish" : "Publish"}
          </button>
          <button
            className="rounded-lg border border-red-200 bg-red-50 px-4 py-2 text-sm font-semibold text-red-700 transition hover:bg-red-100"
            onClick={() => onDelete(post)}
            type="button"
          >
            Delete
          </button>
        </div>
      </div>

      <div className="mt-5 grid gap-4">
        <label className="text-sm font-semibold text-[#191919]">
          Title
          <input
            className="mt-2 w-full rounded-lg border border-[#D9DDE3] px-3 py-3 text-sm outline-none focus:border-[#0A66C2] focus:ring-2 focus:ring-[#0A66C2]/15"
            onChange={(event) => setTitle(event.target.value)}
            value={title}
          />
        </label>
        <label className="text-sm font-semibold text-[#191919]">
          Excerpt
          <textarea
            className="mt-2 min-h-20 w-full rounded-lg border border-[#D9DDE3] px-3 py-3 text-sm outline-none focus:border-[#0A66C2] focus:ring-2 focus:ring-[#0A66C2]/15"
            onChange={(event) => setExcerpt(event.target.value)}
            value={excerpt}
          />
        </label>
        <label className="text-sm font-semibold text-[#191919]">
          SEO Title
          <input
            className="mt-2 w-full rounded-lg border border-[#D9DDE3] px-3 py-3 text-sm outline-none focus:border-[#0A66C2] focus:ring-2 focus:ring-[#0A66C2]/15"
            onChange={(event) => setSeoTitle(event.target.value)}
            value={seoTitle}
          />
        </label>
        <label className="text-sm font-semibold text-[#191919]">
          SEO Description
          <textarea
            className="mt-2 min-h-20 w-full rounded-lg border border-[#D9DDE3] px-3 py-3 text-sm outline-none focus:border-[#0A66C2] focus:ring-2 focus:ring-[#0A66C2]/15"
            onChange={(event) => setSeoDescription(event.target.value)}
            value={seoDescription}
          />
        </label>
        <label className="text-sm font-semibold text-[#191919]">
          Content
          <textarea
            className="mt-2 min-h-72 w-full rounded-lg border border-[#D9DDE3] px-3 py-3 font-mono text-sm leading-6 outline-none focus:border-[#0A66C2] focus:ring-2 focus:ring-[#0A66C2]/15"
            onChange={(event) => setContent(event.target.value)}
            value={content}
          />
        </label>
      </div>
    </article>
  );
}
