import type { Metadata } from "next";
import { BusinessPage } from "@/components/business-page";
import { createSeoMetadata } from "@/lib/seo";

export const metadata: Metadata = createSeoMetadata({
  title: "Privacy Policy | INConnect",
  description:
    "Review how INConnect collects, processes, stores, and uses profile data, AI tool inputs, and service information.",
  path: "/privacy",
});

export default function PrivacyPage() {
  return (
    <BusinessPage
      eyebrow="Privacy Policy"
      title="Privacy Policy"
      intro="This privacy overview explains how INConnect collects, processes, stores, and uses information provided through its LinkedIn intelligence tools. It is informational and not a substitute for legal advice."
      sections={[
        {
          title: "Information we collect",
          body: [
            "INConnect may collect information you provide directly, information generated by the platform, and technical usage data needed to operate and improve the service.",
          ],
          items: [
            "Name",
            "Email address",
            "LinkedIn profile URL",
            "Uploaded LinkedIn Profile PDF",
            "Extracted profile text",
            "Assessment results",
            "Authority score",
            "Professional archetype",
            "Headline Generator inputs and outputs",
            "About Generator inputs and outputs",
            "Blog or admin activity where applicable",
            "Technical usage data",
          ],
        },
        {
          title: "How information is used",
          body: [
            "INConnect uses data to provide assessments, remember user results, personalize recommendations, improve tools, support future Pro features, prevent abuse, and maintain service reliability.",
            "INConnect does not post to LinkedIn on your behalf and does not require direct access to your LinkedIn account.",
          ],
        },
        {
          title: "AI Processing",
          body: [
            "Data may be processed through AI models to generate assessments, profile insights, headlines, About sections, and related professional content.",
            "INConnect uses the OpenAI API server-side. API keys and server credentials are never exposed to the frontend.",
          ],
        },
        {
          title: "Data Storage",
          body: [
            "INConnect uses Supabase for database and storage services. Profile data, generated outputs, and assessment history may be stored to provide memory, returning-user access, and historical insights.",
            "No online service can guarantee perfect security, but INConnect is designed to avoid exposing secret keys or sensitive server credentials to the browser.",
          ],
        },
        {
          title: "Deletion Requests",
          body: [
            "Users can request deletion of their data by contacting INConnect at evgeny.rekling@gmail.com. Please include the email address used with INConnect so the relevant records can be located.",
          ],
        },
        {
          title: "Cookies / Analytics",
          body: [
            "INConnect may use basic analytics and technical cookies to improve the service, understand usage patterns, and maintain platform reliability.",
          ],
        },
      ]}
    />
  );
}
