import { getSupabaseAdminClient } from "@/lib/supabase-admin";

export type BlogPost = {
  authorName: string;
  autoGenerated?: boolean;
  category: string;
  content: string;
  createdAt?: string;
  excerpt: string;
  featured: boolean;
  heroImagePrompt?: string;
  heroImageUrl: string;
  id?: string;
  published?: boolean;
  publishedAt: string;
  seoDescription: string;
  seoTitle: string;
  slug: string;
  title: string;
};

type BlogPostRow = {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  content: string;
  hero_image_prompt: string | null;
  hero_image_url: string | null;
  seo_title: string | null;
  seo_description: string | null;
  published: boolean;
  auto_generated: boolean;
  author_name: string | null;
  created_at: string;
  published_at: string | null;
};

const demoPublishedAt = "2026-06-06T07:00:00.000Z";
const DEFAULT_BLOG_HERO_IMAGE_URL = "/hero-professionals-collage.png";

export const demoBlogPosts: BlogPost[] = [
  {
    authorName: "INConnect Editorial",
    category: "LinkedIn",
    content: [
      "## Start With Positioning",
      "",
      "A strong LinkedIn headline is not just a job title. It should tell people what you do, who you help, and what professional value you are known for.",
      "",
      "For now, this demo article uses placeholder content while the INConnect blog system is being prepared for full editorial publishing.",
      "",
      "## Keep It Specific",
      "",
      "The best headlines are concise, specific, and easy to understand at a glance. Combine your role, industry context, and core expertise in a way that sounds human.",
      "",
      "Avoid adding your name, too many buzzwords, or a long list of disconnected skills.",
      "",
      "## FAQ",
      "",
      "### Should my LinkedIn headline include my name?",
      "",
      "No. Your name already appears next to the headline field, so use the headline for positioning.",
      "",
      "## CTA",
      "",
      "Want to improve your LinkedIn presence? Try INConnect's free AI tools: [Assessment](/assessment), [Headline Generator](/headline-generator), and [About Generator](/about-generator).",
    ].join("\n"),
    excerpt:
      "A practical starting point for writing a LinkedIn headline that communicates role, expertise, and market value without keyword stuffing.",
    featured: true,
    heroImageUrl: DEFAULT_BLOG_HERO_IMAGE_URL,
    publishedAt: demoPublishedAt,
    seoDescription:
      "Learn how to write a clearer LinkedIn headline with role, expertise, market value, and professional positioning.",
    seoTitle: "How to Write a LinkedIn Headline | INConnect",
    slug: "how-to-write-linkedin-headline",
    title: "How to Write a LinkedIn Headline",
  },
  {
    authorName: "INConnect Editorial",
    category: "Industrial Professionals",
    content: [
      "## Make Expertise Visible",
      "",
      "Industrial experience is often deep, practical, and highly valuable, but it can be difficult to communicate clearly on a public profile.",
      "",
      "This placeholder article introduces the direction of the INConnect blog: helping professionals turn complex expertise into clear positioning.",
      "",
      "## Connect Work to Outcomes",
      "",
      "A stronger personal brand connects technical work to business outcomes such as reliability, efficiency, safety, growth, and innovation.",
      "",
      "That connection helps peers, customers, recruiters, and partners understand why your experience matters.",
      "",
      "## FAQ",
      "",
      "### Is LinkedIn useful for industrial professionals?",
      "",
      "Yes. It helps technical, operational, and commercial expertise become easier for partners, employers, and customers to recognize.",
      "",
      "## CTA",
      "",
      "Want to improve your LinkedIn presence? Try INConnect's free AI tools: [Assessment](/assessment), [Headline Generator](/headline-generator), and [About Generator](/about-generator).",
    ].join("\n"),
    excerpt:
      "Industrial professionals can use LinkedIn to make operational expertise, technical credibility, and market knowledge easier to recognize.",
    featured: true,
    heroImageUrl: DEFAULT_BLOG_HERO_IMAGE_URL,
    publishedAt: demoPublishedAt,
    seoDescription:
      "A practical guide to personal branding and LinkedIn positioning for industrial professionals.",
    seoTitle: "Personal Branding for Industrial Professionals | INConnect",
    slug: "personal-branding-industrial-professionals",
    title: "Personal Branding for Industrial Professionals",
  },
  {
    authorName: "INConnect Editorial",
    category: "Leadership",
    content: [
      "## Authority Comes From Consistency",
      "",
      "LinkedIn authority is built through repeated signals: a clear profile, relevant expertise, credible proof, and useful contributions to your professional market.",
      "",
      "This demo article is placeholder content for Blog V1 and will later be replaced with deeper guidance.",
      "",
      "## Turn Experience Into Signals",
      "",
      "Your headline, About section, experience descriptions, and content topics should all support the same professional story.",
      "",
      "When those elements work together, visitors can quickly understand what you stand for and why they should pay attention.",
      "",
      "## FAQ",
      "",
      "### How do professionals build LinkedIn authority?",
      "",
      "They build authority by making their expertise specific, useful, credible, and consistent across their profile and content.",
      "",
      "## CTA",
      "",
      "Want to improve your LinkedIn presence? Try INConnect's free AI tools: [Assessment](/assessment), [Headline Generator](/headline-generator), and [About Generator](/about-generator).",
    ].join("\n"),
    excerpt:
      "Authority on LinkedIn grows when your profile, content, and professional signals consistently reinforce a clear market position.",
    featured: false,
    heroImageUrl: DEFAULT_BLOG_HERO_IMAGE_URL,
    publishedAt: demoPublishedAt,
    seoDescription:
      "Learn how to build authority on LinkedIn through profile clarity, professional positioning, and consistent expertise signals.",
    seoTitle: "How to Build Authority on LinkedIn | INConnect",
    slug: "how-to-build-authority-on-linkedin",
    title: "How to Build Authority on LinkedIn",
  },
];

export async function getPublishedBlogPosts(limit?: number) {
  try {
    const supabase = getSupabaseAdminClient();
    let query = supabase
      .from("blog_posts")
      .select(
        "id, slug, title, excerpt, category, content, hero_image_prompt, hero_image_url, seo_title, seo_description, published, auto_generated, author_name, created_at, published_at",
      )
      .eq("published", true)
      .order("published_at", { ascending: false, nullsFirst: false })
      .order("created_at", { ascending: false });

    if (typeof limit === "number") {
      query = query.limit(limit);
    }

    const { data, error } = await query.returns<BlogPostRow[]>();

    if (error) {
      console.error("Blog published posts lookup failed", error);
      return [];
    }

    return (data ?? []).map(mapBlogPostRow);
  } catch (error) {
    if (!isMissingSupabaseConfigError(error)) {
      console.error("Blog published posts fallback used", error);
      return [];
    }
    return demoBlogPosts;
  }
}

export async function getPublishedBlogPostBySlug(slug: string) {
  try {
    const supabase = getSupabaseAdminClient();
    const { data, error } = await supabase
      .from("blog_posts")
      .select(
        "id, slug, title, excerpt, category, content, hero_image_prompt, hero_image_url, seo_title, seo_description, published, auto_generated, author_name, created_at, published_at",
      )
      .eq("slug", slug)
      .eq("published", true)
      .maybeSingle<BlogPostRow>();

    if (error) {
      console.error("Blog post lookup failed", { slug, error });
    }

    if (data) return mapBlogPostRow(data);
  } catch (error) {
    if (!isMissingSupabaseConfigError(error)) {
      console.error("Blog post fallback lookup used", { slug, error });
    }
  }

  return demoBlogPosts.find((post) => post.slug === slug) ?? null;
}

export function formatBlogDate(value: string) {
  return new Intl.DateTimeFormat("en-US", {
    day: "numeric",
    month: "long",
    year: "numeric",
  }).format(new Date(value));
}

function mapBlogPostRow(row: BlogPostRow): BlogPost {
  return {
    authorName: row.author_name || "INConnect Editorial",
    autoGenerated: row.auto_generated,
    category: row.category,
    content: row.content,
    createdAt: row.created_at,
    excerpt: row.excerpt,
    featured: false,
    heroImagePrompt: row.hero_image_prompt ?? undefined,
    heroImageUrl: row.hero_image_url || DEFAULT_BLOG_HERO_IMAGE_URL,
    id: row.id,
    published: row.published,
    publishedAt: row.published_at || row.created_at,
    seoDescription: row.seo_description || row.excerpt,
    seoTitle: row.seo_title || `${row.title} | LinkedIn Daily`,
    slug: row.slug,
    title: row.title,
  };
}

function isMissingSupabaseConfigError(error: unknown) {
  return error instanceof Error && error.message.includes("Supabase server configuration is missing");
}
